# Generated by Django 4.1 on 2022-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Komputer', 'Komputer'), ('Biurko', 'Biurko'), ('Klawiatury', 'Klawiatury'), ('Myszki', 'Myszki')], default='x', max_length=100),
            preserve_default=False,
        ),
    ]
