# Generated by Django 4.1 on 2022-08-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_alter_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_stars',
            new_name='stars',
        ),
    ]
