# Generated by Django 4.1 on 2022-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_rename_review_stars_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Razer', max_length=255),
            preserve_default=False,
        ),
    ]
