# Generated by Django 4.1 on 2022-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_sold',
            field=models.IntegerField(default=0),
        ),
    ]
