# Generated by Django 4.1 on 2022-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_product_times_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='Jest to krótki opis nie przekreczajacy 200 liter, sluzacy opisaniu danego produktu i sprawdzenia sposobu wyswietlania opisu', max_length=200),
            preserve_default=False,
        ),
    ]
