# Generated by Django 4.1 on 2022-09-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_product_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='times_sold',
            new_name='sold_units',
        ),
    ]
