# Generated by Django 4.1 on 2022-10-03 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0021_alter_product_description_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='FavoriteList',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Komputery', 'Komputery'), ('Biurka', 'Biurka'), ('Klawiatury', 'Klawiatury'), ('Myszki', 'Myszki')], max_length=100),
        ),
    ]
