# Generated by Django 4.1 on 2022-10-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_rename_cart_favoritelist_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Komputery', 'Komputery'), ('Słuchawki', 'Słuchawki'), ('Klawiatury', 'Klawiatury'), ('Monitory', 'Monitory'), ('Myszki', 'Myszki')], max_length=100),
        ),
    ]
