# Generated by Django 4.1 on 2022-10-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Shop.product'),
        ),
    ]
