# Generated by Django 4.1 on 2022-10-07 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0024_alter_favoritelist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_activity', models.CharField(choices=[('login attempt', 'login_attempt'), ('logout', 'logout'), ('login', 'login')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
