# Generated by Django 4.1 on 2022-11-10 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0029_resetpasswordtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='id',
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 10, 13, 8, 17, 290232, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
